# Generated by Django 2.2.4 on 2019-08-05 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eid',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='econtact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ename',
            new_name='name',
        ),
    ]
