# Generated by Django 2.2.4 on 2019-08-05 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_employee_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='manager',
        ),
    ]
