# Generated by Django 2.2.4 on 2019-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0010_auto_20190805_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.ManyToManyField(related_name='employee_name', to='ems.Employee')),
                ('manager', models.ManyToManyField(related_name='manager', to='ems.Employee')),
            ],
        ),
    ]
